CREATE DATABASE IF NOT EXISTS taup_db
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;
 
USE taup_db;
 
CREATE TABLE IF NOT EXISTS urls (
  id INT AUTO_INCREMENT PRIMARY KEY,
  short_code VARCHAR(10) NOT NULL UNIQUE,
  original_url TEXT NOT NULL,
  clicks INT NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);